#possible keybindings
#https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs

#Mod4 = Super key
modkey = "Mod4"
workspaces = []
#tags = ["1", "2", "3", "4"]
tags = [" ", "爵 ", "ﲵ ", " "]

layouts = [ "MainAndVertStack",
            "MainAndHorizontalStack",
            "MainAndDeck",
            "GridHorizontal",
            "EvenHorizontal",
            "EvenVertical",
            "Fibonacci",
            "CenterMain",
            "CenterMainBalanced",
            "Monocle",
            "RightWiderLeftStack",
            "LeftWiderRightStack"]

scratchpad = []
#[[scratchpad]]
#name = "MainTerminal" # This is the name which is referenced when calling (case-sensitive)
#value = "xfce4-terminal" # The command to load the application if it isn't started
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
#focus_behaviour = "Driven"
#focus_behaviour = "ClickTo"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Up"

#[[keybind]]
#command = "Execute"
#value = "leftwm-command SwapScreens"
#modifier = ["modkey"]
#key = "Left"
#
#[[keybind]]
#command = "Execute"
#value = "leftwm-command SwapScreens"
#modifier = ["modkey"]
#key = "Right"

#[[keybind]]
#command = "MoveWindowToNextWorkspace"
#modifier = ["modkey","Shift"]
#key = "Left"
#
#[[keybind]]
#command = "MoveWindowToNextWorkspace"
#modifier = ["modkey","Shift"]
#key = "Right"

#[[keybind]]
#command = "MoveWindowToNextTag"
#value = "true"
#modifier = ["modkey", "Shift"]
#key = "Right"
#
#[[keybind]]
#command = "MoveWindowToPreviousTag"
#value = "true"
#modifier = ["modkey", "Shift"]
#key = "Left"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Up"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "FocusNextTag"
modifier = ["Alt"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Alt", "Shift"]
key = "Tab"

#[[keybind]]
#command = "Execute"
#value = "leftwm-command SwapScreens"
#modifier = ["modkey"]
#key = "Left"
#
#[[keybind]]
#command = "Execute"
#value = "leftwm-command SwapScreens"
#modifier = ["modkey"]
#key = "Right"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
modifier = ["modkey", "Shift"]
key = "4"

