#!/bin/sh
## Workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

## Define colors
bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#434c5e"
bspc config focused_border_color    "#ebcb8b"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color     "#bf616a"

## Set wallpaper
feh --bg-fill --no-fehbg -rz /usr/share/backgrounds/

## Add rules
## but first clear all existing ones
bspc rule -r "*"

## Fullscreen applications
bspc rule -a org.remmina.Remmina state=fullscreen

## Floating applications
bspc rule -a yakuake state=floating
bspc rule -a Xfce4-terminal state=floating

## Tiled applications
#bspc rule -a Xfce4-settings-manager state=tiled

## Pin applications to workspaces
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a Skype desktop='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a org.remmina.Remmina desktop='^5' follow=on

## Lock applications to a certain size
#bspc rule -a Xfce4-terminal state=floating rectangle=900x500+1005+52

##External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode

##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window


## Autostart applications
## Authentication daemon
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Notifications daemon
/usr/lib/xfce4/notifyd/xfce4-notifyd &
#dunst &

## Number pad on
numlockx on &

## Hotkeys daemon and tweaks
[[ $(pgrep -x sxhkd) ]] && pkill sxhkd
sxhkd &

setxkbmap -option caps:swapescape
setxkbmap -option altwin:swap_alt_win

## XFCE power manager
#xfce4-power-manager &

## Picom
#[[ $(pgrep -x picom) ]] && pkill picom
picom &

## Polybar
~/.config/polybar/launch.sh

## Systray applets
nm-applet &
blueberry-tray &
kdeconnect-indicator &

## Redshift
[[ $(pgrep -x redshift) ]] && pkill redshift
sleep 4 && redshift &

