#!/bin/bash
## Workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

## Define colors
bspc config normal_border_color     '#4c566a'
bspc config active_border_color     '#434c5e'
bspc config focused_border_color    '#ebcb8b'
bspc config presel_feedback_color   '#5e81ac'
bspc config urgent_border_color     '#bf616a'

## Add rules
## but first clear all existing ones
bspc rule -r '*'

## Fullscreen applications


## Floating applications
bspc rule -a org.remmina.Remmina state=floating
bspc rule -a Galculator state=floating

## Pseudo-tiled applications
#bspc rule -a Galculator state=pseudo_tiled

## Tiled applications
bspc rule -a Zoiper state=tiled split_ratio=0.85

## Lock applications to a certain size
#bspc rule -a Xfce4-terminal state=floating rectangle=900x500+1005+52

## Pin applications to workspaces
## Workspace 1
bspc rule -a Brave-browser desktop='^1' follow=on

## Workspace 2
bspc rule -a org.remmina.Remmina desktop='^2'

## Workspace 3
bspc rule -a Alacritty desktop='^3' follow=on

## Workspace 4
bspc rule -a Thunar desktop='^4' follow=on

## Workspace 5
bspc rule -a Steam desktop='^5' follow=on
bspc rule -a Lutris desktop='^5' follow=on

## Workspace 6
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Skype desktop='^6'
bspc rule -a Zoiper desktop='^6'

## Set wallpaper
feh --bg-fill --no-fehbg -rz ~/pictures/backgrounds/reality

## Autostart applications
## Authentication daemon
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Keyboard
## Layouts
setxkbmap -option
setxkbmap -layout us,ru -option grp:sclk_toggle,caps:swapescape

## Number pad on
numlockx on &

## Hotkey daemon
[[ $(pgrep -x sxhkd) ]] || sxhkd &

## Notifications daemon
[[ $(pgrep -x dunst) ]] || dunst &

## Picom
[[ $(pgrep -x picom) ]] || picom &

## Redshift
[[ $(pgrep -x redshift) ]] || redshift &

## Flameshot
[[ $(pgrep -x flameshot) ]] || flameshot &

## Polybar
~/.config/polybar/launch.sh

## VPN
[[ $(pgep -x openvpn) ]] || sudo systemctl start openvpn-client@nl.service

## Telegram
[[ $(pgrep telegram) ]] || telegram-desktop &

## Systray applets
nm-applet &
blueman-applet &
kdeconnect-indicator &

