#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# keybindings daemon
sxhkd &

# diversity of apps to start
nm-applet &
#pamac-tray &
xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/picom.conf &> /dev/null &
  #picom --config $HOME/.config/leftwm/themes/current/picom.conf --experimental-backends &> /dev/null &
  #picom &> /dev/null &
  #picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $HOME/.config/leftwm/themes/current/compton.conf &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --no-fehbg -rz /usr/share/backgrounds/
fi

$SCRIPTPATH/launch.sh

